### ISSUE TITLE
Create a Colour Scheme

### ISSUE THREAD

**Issue by nsdeschenes** [nsdeschenes/nsdeschenes.ca#10]
Every great site has a colour scheme so why shouldn't mine?!

**Comment by peacheym** [comment]
This will be a great site and will have an equally great colour scheme! 🎨

**Comment by nsdeschenes** [comment]
@peacheym what do you think of this first possible schemes:
- ![#222831](https://via.placeholder.com/15/222831/000000?text=+) `#222831` &#8592; Main Background Color
- ![#393E46](https://via.placeholder.com/15/393E46/000000?text=+) `#393E46` &#8592; Background Highlight Color
- ![#FFD369](https://via.placeholder.com/15/FFD369/000000?text=+) `#FFD369` &#8592; Highlights on Hover, etc.
- ![#EEEEEE](https://via.placeholder.com/15/EEEEEE/000000?text=+) `#EEEEEE` &#8592; Main Text

**Comment by nsdeschenes** [comment]
Possibly purples for text when being highlighted in yellow:
- ![#D74FFF](https://via.placeholder.com/15/D74FFF/000000?text=+) `#D74FFF`
- ![#9840B3](https://via.placeholder.com/15/9840B3/000000?text=+) `#9840B3`

**Comment by FestiveKyle** [comment]
+1 for #9840B3 (more contrast)

**Comment by peacheym** [comment]
Hi @nsdeschenes -- I've just consulted with my in-house design group, and they agree that your proposed colour scheme (including `#9840B3`) will make for an excellent visual experience.

All in all, LGTM!

**Comment by nsdeschenes** [comment]
Final colour scheme:
- ![#222831](https://via.placeholder.com/15/222831/000000?text=+) `#222831` &#8592; Main Background Color
- ![#393E46](https://via.placeholder.com/15/393E46/000000?text=+) `#393E46` &#8592; Background Highlight Color
- ![#FFD369](https://via.placeholder.com/15/FFD369/000000?text=+) `#FFD369` &#8592; Highlights on Hover, etc.
- ![#9840B3](https://via.placeholder.com/15/9840B3/000000?text=+) `#9840B3` &#8592; Text on Hightlights
- ![#EEEEEE](https://via.placeholder.com/15/EEEEEE/000000?text=+) `#EEEEEE` &#8592; Main Text
